# Generated by Django 3.2.4 on 2021-08-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(default='null', max_length=30)),
                ('Last_name', models.CharField(default='null', max_length=30)),
                ('Email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('Vehicle', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
    ]
