# Generated by Django 3.2.4 on 2021-08-30 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Automaton', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.AddField(
            model_name='bookings',
            name='Time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
