# Generated by Django 3.2.4 on 2021-08-31 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automaton', '0004_alter_bookings_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 16, 16, 44, 220062)),
        ),
    ]
